### ISSUE TITLE
feat: add a LICENSE file

### ISSUE THREAD

**Issue by BernhardRode** [tmcw/jsonlint#3]
Hi,

I'm using 

from
https://github.com/mapbox/jsonlint
which is a fork of your lines-primitive branch.

In the fork, the README has been changed, therefore the LICENSE disappeared.
I'm contacting you, as that the fork has no issues enabled =) 

I'm going to create PRs for projects.

**Comment by tmcw** [comment]
Thanks for the note, but you'll need to contact the mapbox folks some other way, I don't work there or have commit access anymore.
